### ISSUE TITLE
how to use GPU

### ISSUE THREAD

**Issue by limulimu** [Cyberbolt/Cemotion#6]
我把torch替换为了CUDA版本的，但是就无法运行了
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)

CPU版本太慢了，能麻烦指导一下吗

**Comment by Cyberbolt** [comment]
模型是在苹果 M1 上训练的，为了兼容性只保留了 CPU 推理

**Comment by Cyberbolt** [comment]
已更新，现在会自动识别并调用 NVIDIA 和 Apple Silicon GPUs
