### ISSUE TITLE
默认安装torch最新2.1.1，但是torchvision 0.13.0 requires torch==1.12.0，降级后提示这个库必须要torch2.0，自相矛盾了属于是

### ISSUE THREAD

**Issue by heavytable** [Cyberbolt/Cemotion#8]

**Comment by Cyberbolt** [comment]
install_requires=[
        'tqdm>=4.64.1',
        'joblib>=1.0.0',
        'requests>=2.25.1',
        'numpy>=1.19.5',
        'torch>=2.0.0',
        'transformers==4.24.0',
    ]    

这是项目的依赖要求，你可以新建一个全新的虚拟环境试试
